<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $user = $ow->getUser();
    
    $inPrivate = false;
    $req = $_REQUEST;
    if (isset($req["uri"])) {
        $beuri = urldecode($req["uri"]);
        $checkQuery = 'SELECT ?t WHERE {<'.$beuri.'> <'.EF_RDF_TYPE.'> ?t}';
        if (!$user->isAnonymousUser()) {
            $privatespace = getPrivateSpace($ow);
            if ($privatespace !== false) {
                $privatemodel = new Erfurt_Rdf_Model($privatespace[0]);
                $inPrivate = $privatemodel->sparqlQuery($checkQuery);
                $inPrivate = ( $inPrivate == array() ? false : true);
            }
        }
        if (isset($_REQUEST["page"]) && $inPrivate && (
            ($_REQUEST["page"] == "businessentity") ||
            ($_REQUEST["page"] == "publishbusinessentity") ||
            (isset($GLOBALS["IAmBusiness"]) && $GLOBALS["IAmBusiness"] == true)
            ))
        {
?>
<div id="businessbox" class="rightbox">
    <h3>Business entity</h3>
    <p>
    <a href="?page=publishbusinessentity&amp;uri=<?php echo urlencode($_GET["uri"]); ?>" class="formbutton">Publish business</a>
    </p>
</div>
<?php
        }
    }