<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $user = $ow->getUser();
    
    
?>
<?php if (!$user->isAnonymousUser()) {
    $groups = getContractUseroups($ow);
?>
<div id="mycontractsbox" class="leftbox">
    <h3>Private space</h3>
    <ul>
        <li><a href="?page=searchmycontracts&amp;cht=<?php echo genChT(); ?>">Contracts</a></li>
        <li><a href="?page=searchmysuppliers&amp;cht=<?php echo genChT(); ?>">Business entities</a></li>
        <?php if ($groups["contractor"]) { ?>
        <li><a href="?page=newcontract">Create contract</a></li>
        <?php } ?>
        <?php if ($groups["any"]) { ?>
        <li><a href="?page=newbusinessentity">Create business entity</a></li>
        <?php } ?>
    </ul>
</div>
<?php }