<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $user = $ow->getUser();
    // if (!$user->isAnonymousUser()) echo "Contracts of other authorities"; else echo "Public contracts"; 
?>
<div id="othercontractsbox" class="leftbox">
    <h3>Public space</h3>
    <ul>
        <li><a href="?page=searchcontracts&amp;cht=<?php echo genChT(); ?>">Contracts</a></li>
        <li><a href="?page=searchsuppliers&amp;cht=<?php echo genChT(); ?>">Business entitites</a></li>
    </ul>
</div>