<?php
    //print_r(get_object_vars($this));
    require_once($this->basePath."/lib/my.lib.php");
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $GLOBALS["cBaseUri"] = $this->baseUri;
    $GLOBALS["wBaseUri"] = $this->wikiBaseUrl;
?>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link rel="stylesheet" type="text/css" href="<?php echo $this->themeUrlBase ?>/styles/default.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/main.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/elements.css" media="screen" />
    
    <!-- jQuery -->
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script>

    <!--script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-fluid16.js"></script-->

    <title><?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?> :: LOD2</title>
</head>
<body about="<?php echo $this->resourceUri?>">
<div id="bodybox">
    <div id="headbox">
        <h1>Public contract filling app<a href="/?cht=<?php echo genChT(); ?>">#</a></h1>
    </div>
    <div id="leftbox" class="bodybox">
        <?php echo $this->partial('contracts/parts/account.phtml', $templateData) ?>
        <?php echo $this->partial('contracts/parts/mycontracts.phtml', $templateData) ?>
        <?php echo $this->partial('contracts/parts/othercontracts.phtml', $templateData) ?>
    </div>

    <div id="centralbox" class="bodybox">
        <?php echo $this->partial('contracts/parts/main.phtml', $templateData) ?>
    </div>

    <div id="rightbox" class="bodybox">
        <?php echo $this->partial('contracts/parts/filter.phtml', $templateData) ?>
        <?php echo $this->partial('contracts/parts/businessentity.phtml', $templateData) ?>
    </div>
</div>
</body>
</html>