<?php

/**
 * OntoWiki navigation entry list template
 */
$odd = true;
?>
<ol class="bullets-none separated">
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-createcontract" class="navigation navList contracts-button" name="pcfa-createcontract"
            href="javascript:createInstanceFromClassURI('http://purl.org/procurement/public-contracts#Contract')" >
            New public contract
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-createbusiness" class="navigation navList contracts-button" name="pcfa-createbusiness"
            href="javascript:createInstanceFromClassURI('http://purl.org/goodrelations/v1#BusinessEntity')" >
            New business entity
        </a>
    </li>
</ol>