<?php

/**
 * OntoWiki navigation entry list template
 */
$odd = true;
?>
<ol class="bullets-none separated">
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-createcontract" class="navigation navList contracts-button" name="pcfa-createcontract"
            href="/contracts/newcontract/" >
            New public contract
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-createbusiness" class="navigation navList contracts-button" name="pcfa-createbusiness"
            href="/contracts/newbusinessentity/" >
            New business entity
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-preferences" class="navigation navList contracts-button" name="pcfa-preferences"
            href="/application/preferences/" >
            Preferences
        </a>
    </li>
</ol>