<?php

$odd = true;

?>
<p class="curResourceName" style="overflow:hidden;">Business entity:
    <a href="<?php echo $this->data["ow"]->getUrlBase(),"resource/properties/?r=",urlencode($this->data["res"]->__toString()); ?>">
        <?php echo (string)$this->data["res"]; ?>
    </a>
</p>
<ol class="bullets-none separated">
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-ppin" class="navigation navList contracts-button" name="contracts-ppin"
            href="<?php echo $this->data["ow"]->getUrlBase(),"contracts/publishbusiness/?r=",urlencode($this->data["res"]->__toString()); ?>" >
            Publish business entity
        </a>
    </li>
</ol>