<?php

$odd = true;

?>
<p class="curResourceName" style="overflow:hidden;">Public contract:
    <a href="<?php echo $this->data["ow"]->getUrlBase(),"resource/properties/?r=",urlencode($this->data["res"]->__toString()); ?>">
        <?php echo $this->data["res"]->__toString(); ?>
    </a>
</p>
<ol class="bullets-none separated">
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-ppin" class="navigation navList contracts-button" name="contracts-ppin"
            href="/contracts/publishpriornotice" >
            Publish prior information notice
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-pcn" class="navigation navList contracts-button" name="contracts-pcn"
            href="/contracts/publishnotice" >
            Publish contract notice
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-ct" class="navigation navList contracts-button" name="contracts-ct"
            href="/contracts/createtender" >
            Create tender
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-cc" class="navigation navListcontracts-button" name="contracts-cc"
            href="/contracts/cancelcontract" >
            Cancel contract
        </a>
    </li>
</ol>