<?php
$odd = false;
$ow = OntoWiki::getInstance();
$resource = OntoWiki::getInstance()->selectedResource;
$resource_uri = (string)$resource;
$not_linked = $this->placeholder('tender_not_linked')->getValue();
?>
<h2>Award tender</h2>
<h3>Tender <em><?php echo $resource_uri; ?></em></h3>
<?php
if ($not_linked) { ?>
<p class="messagebox warning">This tender is not assigned to any contract.</p>
<?php } else {
    $resource_contract_uri = $this->placeholder('tender_contract')->getValue();
    $contract_already_awarded = $this->placeholder('contract_already_awarded')->getValue();
    $tender_awarded = $this->placeholder('tender_awarded')->getValue();
    $contract_notice_already_published = $this->placeholder('contract_notice_already_published')->getValue();
?>
<h3>for contract <em><?php echo $resource_contract_uri; ?></em></h3>

<?php if ($contract_notice_already_published) { ?>
<p class="messagebox warning">Contract notice was already published.</p>
<?php } ?>

<?php if ($contract_already_awarded !== false) { ?>
<p class="messagebox warning">Tender <em><?php echo $contract_already_awarded; ?></em> was already awarded for this contract.</p>
<?php } ?>

<?php if ($tender_awarded) { ?>
<p class="messagebox success">Tender was successfully awarded.</p>
<?php } else { ?>
<p class="messagebox error">Tender was not awarded.</p>
<?php } ?>

<?php } ?>

<p class="messagebox"><a href="<?php echo $ow->getUrlBase(),"resource/properties/?r=",urlencode($resource_uri); ?>">Back to tender</a></p>

<?php 
