<?php
$odd = true;
?>
<div id="contracts-contracttoolbox-content" class="width99">
<p class="curResourceName" style="overflow:hidden;">Public contract:
    <a href="<?php echo $this->data["ow"]->getUrlBase(),"resource/properties/?r=",urlencode((string)$this->data["res"]); ?>">
        <?php echo $this->data["res"]->__toString(); ?>
    </a>
</p>
<ol class="bullets-none separated">
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-ppin" class="navigation navList contracts-button" name="contracts-ppin"
            href="/contracts/publishpriornotice" >
            Publish prior information notice
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-pcn" class="navigation navList contracts-button" name="contracts-pcn"
            href="/contracts/publishnotice" >
            Publish contract notice
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-ct" class="navigation navList contracts-button" name="contracts-nt"
            href="/contracts/newtender" >
            Create tender
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="contracts-cc" class="navigation navListcontracts-button" name="contracts-cc"
            href="/contracts/cancelcontract" >
            Cancel contract
        </a>
    </li>
</ol>
<?php
if( isset($this->stateView) ){
    echo $this->stateView;
} 
?>    
</div>
<?php 
