<?php

/**
 * OntoWiki contracts user type module template
 */
$odd = true;
$ow = OntoWiki::getInstance();
//set private data space as active model
$privatedataspace = ContractsHelper::getUserDataSpace();
if ($privatedataspace !== false) {
    $privatedataspace = $privatedataspace[0];
    $store = OntoWiki::getInstance()->erfurt->getStore();
    $model = $store->getModel($privatedataspace);
    OntoWiki::getInstance()->selectedModel = $model;
}
//$groups = ContractsHelper::getContractUseroups();

$suurl = $this->data["url"]; //$ow->getUrlBase()."contracts/setusertype";
$contractor = $this->data["contractor"]; //$groups["contractor"];
$supplier = $this->data["supplier"]; //$groups["supplier"];
$ownbusiness = ContractsHelper::getUserBusiness();

?>

<ol class="bullets-none separated">
    <li>
        <small>
        Member of groups:
        <ul>
        <?php
            if ($contractor) echo "<li>Contractors</li>";
            if ($supplier) echo "<li>Suppliers</li>";
            if (!$contractor && !$supplier) echo "<li>none</li>";
        ?>
        </ul>
        <!-- <br /> -->
        </small>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-usercontractor" class="navigation navList" name="pcfa-usercontractor"
            href="<?php echo $suurl,"/",($this->data["contractor"]?"?contractor=no":"?contractor=yes"); ?>" >
            <?php echo ($this->data["contractor"]?"I am not contractor":"I am contractor"); ?>
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-usersupplier" class="navigation navList" name="pcfa-usersupplier"
            href="<?php echo $suurl,"/",($this->data["supplier"]?"?supplier=no":"?supplier=yes"); ?>" >
            <?php echo ($this->data["supplier"]?"I am not supplier":"I am supplier"); ?>
        </a>
    </li>
<?php
if ($contractor || $supplier) {
    if ($ownbusiness === false) {
?>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-businessself" class="navigation navList" name="pcfa-businessself"
            href="<?php echo $ow->getUrlBase(); ?>contracts/newbusinessentity/?self=true" >
            Create own business entity
        </a>
    </li>
<?php } else { ?>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-businessself" class="navigation navList" name="pcfa-businessself"
            href="<?php echo $ow->getUrlBase(); ?>resource/properties/?r=<?php echo urlencode($ownbusiness[0]); ?>" >
            Edit own business entity details
        </a>
    </li>
<?php
    }
} else {
?>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <small>You must be either contractor or supplier to edit your business entity.</small>
    </li>
<?php } ?>
</ol>

<?php