<?php
$odd = true;
//echo urldecode("http://ontowiki2.ranec.net/list?init&instancesconfig=%7B%22filter%22%3A%5B%7B%22rdfsclass%22%3A%22http%3A%5C%2F%5C%2Fpurl.org%5C%2Fprocurement%5C%2Fpublic-contracts%23Contract%22%2C%22mode%22%3A%22rdfsclass%22%7D%5D%7D");
?>
<div id="contracts-content" class="width99">
<ol class="bullets-none separated">
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-preferences" class="navigation navList contracts-button" name="pcfa-preferences"
            href="/application/preferences/" >
            Preferences
        </a>
    </li>
    <li></li>
<?php if ($this->data["onmodel"]) { ?>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-createcontract" class="navigation navList contracts-button" name="pcfa-createcontract"
            href="/contracts/newcontract/" >
            New public contract
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-createbusiness" class="navigation navList contracts-button" name="pcfa-createbusiness"
            href="/contracts/newbusinessentity/" >
            New business entity
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-list-contract" class="navigation navList contracts-button" name="pcfa-preferences"
            href="http://ontowiki2.ranec.net/list?init&amp;instancesconfig=<?php echo urlencode('{"filter":[{"rdfsclass":"http:\/\/purl.org\/procurement\/public-contracts#Contract","mode":"rdfsclass"}]}'); ?>" >
            Show all public contracts
        </a>
    </li>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-list-contract" class="navigation navList contracts-button" name="pcfa-preferences"
            href="http://ontowiki2.ranec.net/list?init&amp;instancesconfig=<?php echo urlencode('{"filter":[{"rdfsclass":"http:\/\/purl.org\/goodrelations\/v1#BusinessEntity","mode":"rdfsclass"}]}'); ?>" >
            Show all business entities
        </a>
    </li>
<?php } else { ?>
    <li class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <a id="pcfa-list-contract" class="navigation navList contracts-button" name="pcfa-preferences"
            href="/model/select?m=<?php $uds = ContractsHelper::getUserDataSpace(); echo urlencode($uds[0]); ?>" >
            Enter private data space
        </a>
    </li>
<?php } ?>
</ol>
<?php
if( isset($this->stateView) ){
    echo $this->stateView;
} 
?>    
</div>
<?php 