<?php
$odd = false;
$store = OntoWiki::getInstance()->erfurt->getStore();//$this->placeholder('erfurt_store')->getValue();
$model = OntoWiki::getInstance()->selectedModel;

?>

<h2>New business entity</h2>
<h3>in model <em><?php echo (string)$model; ?></em></h3>
<?php
if (!$model->isEditable()) { /* OntoWiki::getInstance()->erfurt->getAc()->isModelAllowed('edit',$model->getUri()) */ 
    echo '<p class="messagebox warning">This model is not editable, please select your personal data space.</p>';
}
$usergroups = ContractsHelper::getContractUseroups();
if (!$usergroups["any"]) {
    echo '<p class="messagebox error">You must be contractor or supplier to be able to create business entities.</p>';
    echo '<p class="messagebox info">You can visit <a href="/application/preferences">preferences</a> to change your user type.</p>';
}
else if (!isset($_POST["prop_gr_legalName"])) {
?>
<form id="newbusiness" name="newbusiness" method="post" action="<?php if (isset($_GET["self"])) echo "?self=",$_GET["self"]; ?>">
<table class="separated-vertical">
<tbody>
    <tr>
        <td width="120">
            <a class="hasMenu" href="/view/r/gr%3AlegalName">gr:legalName</a>
        </td>
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu"> </div>
                <input id="prop_gr_legalName" name="prop_gr_legalName" class="text" type="text" value="" style="width: 100%;" />
            </div>
        </td>
        <td>The legal name of the business entity.</td>
    </tr>
    <tr>
        <td width="120">
            <a class="hasMenu" href="/view/r/br%3AofficialNumber">br:officialNumber</a>
        </td>
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu"> </div>
                <input id="prop_br_officialNumber" name="prop_br_officialNumber" class="text" type="text" value="" style="width: 100%;" />
            </div>
        </td>
        <td>Official identification number.</td>
    </tr>
    <tr>
        <td width="120">
            <a class="hasMenu" href="/view/r/vcard%3Aadr">vcard:adr</a>
        </td>
        <td></td>
        <td>A postal or street address of a person.</td>
    </tr>
    <tr>
        <td width="140">
            &nbsp;&nbsp;&nbsp;<a class="hasMenu" href="/view/r/vcard%3Acountry-name">vcard:country-name</a>
        </td>
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu"> </div>
                <input id="prop_vcard_country-name" name="prop_vcard_country-name" class="text" type="text" value="" style="width: 100%;" />
                            </div>
        </td>
        <td>The country of a postal address. Use two-letter code according to <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements" target="_blank">ISO 3166-1 alpha-2</a>; e.g. CZ or GB</td>
    </tr>
    <tr>
        <td width="140">
            &nbsp;&nbsp;&nbsp;<a class="hasMenu" href="/view/r/vcard%3Alocality">vcard:locality</a>
        </td>
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu"> </div>
                <input id="prop_vcard_locality" name="prop_vcard_locality" class="text" type="text" value="" style="width: 100%;" />
            </div>
        </td>
        <td>The locality (e.g., city) of a postal address.</td>
    </tr>
    <tr>
        <td width="140">
            &nbsp;&nbsp;&nbsp;<a class="hasMenu" href="/view/r/vcard%3Apostal-code">vcard:postal-code</a>
        </td>
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu"> </div>
                <input id="prop_vcard_postal-code" name="prop_vcard_postal-code" class="text" type="text" value="" style="width: 100%;" />
            </div>
        </td>
        <td>The postal code (e.g., U.S. ZIP code) of a postal address.</td>
    </tr>
    <tr>
        <td width="140">
            &nbsp;&nbsp;&nbsp;<a class="hasMenu" href="/view/r/vcard%3Astreet">vcard:street</a>
        </td>
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu"> </div>
                <input id="prop_vcard_street" name="prop_vcard_street" class="text" type="text" value="" style="width: 100%;" />
            </div>
        </td>
        <td>The street address of a postal address.</td>
    </tr>
</tbody>
</table>
<a class="button init-resource" href="javascript:document.newbusiness.submit();" >
<img src="/extensions/themes/silverblue/images/icon-editadd.png" /> <?php /* //TODO theme */ ?>
<span>Create business entity</span>
</a>
</form>
<?php } else {
//$resource = OntoWiki::getInstance()->selectedResource;
//$rurl = urlencode((string)$resource->getUri());
$resname = $this->placeholder('added_resource')->getValue();
print_r($resname);
$isself = $this->placeholder('is_own_business')->getValue();
if ($resname !== false) {
    $rurl = urlencode($resname);
    echo '<p class="messagebox success">Business entity successfully created.</p>';
    echo '<p>You can see it <a href="/resource/properties/?r=',$rurl,'">here</a>.</p>';
    if ($isself)
        echo '<p class="messagebox info">This business entity is linked to your account. (Describing your company.)</p>';
}
else
    echo '<p class="messagebox error">Business entity was not created. Possible permision problem.</p>';
?>

<?php }

/*$usergroups = ContractsHelper::getContractUseroups();
print_r($usergroups);*/
