<?php
$odd = false;
$ow = OntoWiki::getInstance();
$store = OntoWiki::getInstance()->erfurt->getStore();//$this->placeholder('erfurt_store')->getValue();
$model = OntoWiki::getInstance()->selectedModel;

?>


<h2>New contract</h2>
<h3>in model <em><?php echo (string)$model; ?></em></h3>
<?php if (!$model->isEditable()) { /* OntoWiki::getInstance()->erfurt->getAc()->isModelAllowed('edit',$model->getUri()) */ ?>
<p class="messagebox error">This model is not editable, please select your personal data space.</p>
<?php } else { 
$resname = $this->placeholder('added_resource')->getValue();
if ($resname === false) {
    echo '<p class="messagebox error">New contract was not created.</p>';
    $usergroups = ContractsHelper::getContractUseroups();
    if (!$usergroups["contractor"])
        echo '<p class="messagebox info">You must be contractor to be able to create new contracts. Check your <a href="',$ow->getUrlBase(),'application/preferences">preferences</a>.</p>';
    $businesses = ContractsHelper::getUserBusiness();
    if ($businesses === false)
        echo '<p class="messagebox info">Before creating contracts, you must create your own business entity from your <a href="',$ow->getUrlBase(),'application/preferences">preferences</a>.</p>';
} else {
    $rurl = urlencode($resname);
    echo '<p class="messagebox success">New contract created.</p>';
    echo '<p>To edit its properties continue <a href="',$ow->getUrlBase(),'resource/properties/?r=',$rurl,'">here</a>.</p>';
}
}