<?php
$odd = false;
$published_business = $this->placeholder('published_business')->getValue();
$already_published = $this->placeholder('already_published')->getValue();
$resource = (string)OntoWiki::getInstance()->selectedResource;
?>

<h2>Publish business entity</h2>
<h3><em><?php echo $resource; ?></em></h3>
<?php if ($already_published) { ?>
<p class="messagebox warning">Business entity was already published to public data space. Republishing...</p>
<?php } ?>
<?php if ($published_business) { ?>
<p class="messagebox success">Business entity was successfully published to public data space.</p>
<?php } else { ?>
<p class="messagebox error">Business entity could <strong>not</strong> be published to public data space.</p>
<?php } ?>
