<?php
$odd = false;
$published_priornotice = $this->placeholder('published_priornotice')->getValue();
$already_published = $this->placeholder('already_published')->getValue();
$missing = $this->placeholder('missing')->getValue();
$price_problem = $this->placeholder('price_problem')->getValue();
$resource = (string)OntoWiki::getInstance()->selectedResource;
?>
<h2>Publish prior information notice</h2>
<h3><em><?php echo $resource; ?></em></h3>

<?php if ($already_published) { ?>
<p class="messagebox error">Prior information notice was already published to public data space.</p>
<?php } ?>

<?php if ($missing != array()) { ?>
<p class="messagebox error">Missing required properties:</p>
<ul>
    <?php
    foreach ($missing as $prop)
        echo "<li>",$prop,"</li>";
    ?>
</ul><br />
<?php } ?>

<?php if ($price_problem) { ?>
<p class="messagebox error">Problem with price properties. Either <em>pc:estimatedPrice</em> or both <em>pc:estimatedPricelower</em> and <em>pc:estimatedPriceUpper</em> must be set.</p>
<?php } ?>

<?php if ($published_priornotice) { ?>
<p class="messagebox success">Prior information notice was successfully published to public data space.</p>
<?php } else { ?>
<p class="messagebox error">Prior information notice could <strong>not</strong> be published to public data space.</p>
<?php } ?>

