<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $user = $ow->getUser();
    $baseUri = $GLOBALS["cBaseUri"];
    $wikiBaseUri = $GLOBALS["wBaseUri"];
    $redirectUri = $wikiBaseUri."?page=welcome";
    
    if (!$user->isAnonymousUser()) {
        //just load preferences
        echo $this->partial('contracts/pages/preferences.phtml', $templateData);
    }
    else {
        //?page=login
?>
<form action="<?php echo $wikiBaseUri; ?>application/login" method="post" name="locallogin">
    <input type="hidden" name="logintype" value="locallogin" />
    <input type="hidden" name="redirect-uri" value="<?php echo $redirectUri ?>" />
<table class="logintable">
    <tr>
        <td>Username</td>
        <td><input class="text" type="text" id="username" name="username" value="" /></td>
    </tr>
    <tr>
        <td>Password</td>
        <td><input class="password" type="password" id="password" name="password" /></td>
    </tr>
    <tr>
        <td></td>
        <td class="checkboxradio">
            <input class="checkbox inlinecheckbox" type="checkbox" id="login-save" name="login-save" />
            Remember me
        </td>
    </tr>
    <tr>
        <td></td>
        <td><input class="button" id="submit-login" type="submit" name="submitlogin" value="Login" /></td>
    </tr>
</table>
<?php
}
