<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $erfurt = $ow->erfurt;
    $store = $erfurt->getStore();
    $user = $ow->getUser();
    $baseUri = $GLOBALS["cBaseUri"];

?>
    <h2>New business entity</h2>
	<div id="form_container">
		<form name="contractcreate"  id="form_473035" class="appnitro"  method="post" action="?page=contract&amp;new=new">
					<!--<div class="form_description">
			<h2>Untitled Form</h2>
			<p>This is your form description. Click here to edit.</p>
		</div>	-->					
			<ul >

					<li id="li_1" >
		<label class="description" for="dct:title">Name </label>
		<div>
			<input id="dct:title" name="dct:title" class="element text large" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_1"><small>dct:title<br />
A name given to the contract.</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="dct:description">Description </label>
		<div>
			<textarea id="dct:description" name="dct:description" class="element textarea small"></textarea> 
		</div><p class="guidelines" id="guide_2"><small>dct:description<br />
An account of the contract.</small></p> 
		</li>

					<li class="buttons">
			    <input type="hidden" name="form_id" value="473035" />
			    
				<input id="saveForm" class="button_text button" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
	</div>

<?php 

