<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $erfurt = $ow->erfurt;
    $store = $erfurt->getStore();
    $user = $ow->getUser();
    
    //= SETUP ==================================================================
    /*$configModel = $store->getModel('http://localhost/OntoWiki/Config/',false);
    $store->deleteMatchingStatements($configModel->getModelIri(),
        'http://ns.ontowiki.net/SysOnt/Anonymous',
        'http://ns.ontowiki.net/SysOnt/grantModelView',
        array('value' => 'http://ns.ontowiki.net/SysOnt/AnyModel', 'type'  => 'uri'),
        false);
    $store->deleteMatchingStatements($configModel->getModelIri(),
        'http://ns.ontowiki.net/SysOnt/Anonymous',
        'http://ns.ontowiki.net/SysOnt/grantModelEdit',
        array('value' => 'http://ns.ontowiki.net/SysOnt/AnyModel', 'type'  => 'uri'),
        false);
    $store->addStatement($configModel->getModelIri(),
        'http://ns.ontowiki.net/SysOnt/Admin',
        'http://ns.ontowiki.net/SysOnt/grantModelEdit',
        array('value' => 'http://localhost/OntoWiki/Config/', 'type'  => 'uri'),
        false);*/
    //add model from virtuoso    
    /*$configModel = $store->getModel('http://localhost/OntoWiki/Config/',false);    
    $store->addStatement($configModel->getModelIri(),
        'http://contracts.opendata.cz/resource/dataset/test',
        'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
        array('value' => 'http://ns.ontowiki.net/SysOnt/Model', 'type'  => 'uri'),
        false);
    $store->addStatement($configModel->getModelIri(),
        'http://ns.ontowiki.net/SysOnt/Anonymous',
        'http://ns.ontowiki.net/SysOnt/grantModelView',
        array('value' => 'http://contracts.opendata.cz/resource/dataset/test', 'type'  => 'uri'),
        false);*/
    /*$configModel = $store->getModel('http://localhost/OntoWiki/Config/',false);    
    $store->addStatement($configModel->getModelIri(),
        'http://purl.org/weso/datasets/pscs/cpv/2008/',
        'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
        array('value' => 'http://ns.ontowiki.net/SysOnt/Model', 'type'  => 'uri'),
        false);
    $store->addStatement($configModel->getModelIri(),
        'http://ns.ontowiki.net/SysOnt/Anonymous',
        'http://ns.ontowiki.net/SysOnt/grantModelView',
        array('value' => 'http://purl.org/weso/datasets/pscs/cpv/2008/', 'type'  => 'uri'),
        false);*/
    $setup = false; //rewrite to true and load page once then change back to false
    if ($setup) {
        echo "Configuring...";
        $configModel = $store->getModel('http://localhost/OntoWiki/Config/',false);
        $store->addStatement($configModel->getModelIri(),
            'http://ns.ontowiki.net/SysOnt/Anonymous',
            'http://ns.ontowiki.net/SysOnt/grantModelView',
            array('value' => 'http://contracts.opendata.cz/web/', 'type'  => 'uri'),
            false);
        $store->addStatement($configModel->getModelIri(),
                'http://ns.ontowiki.net/SysOnt/Anonymous',
                'http://ns.ontowiki.net/SysOnt/grantModelView',
                array('value' => 'http://ld.opendata.cz/resource/', 'type'  => 'uri'),
                false);
        $options['use_ac'] = false;
        $store->deleteMatchingStatements($configModel->getModelIri(),
                'http://ns.ontowiki.net/SysOnt/Anonymous',
                'http://ns.ontowiki.net/SysOnt/grantModelView',
                array('value' => 'http://ns.ontowiki.net/SysOnt/AnyModel ', 'type'  => 'uri'), $options); //false??
        $store->deleteMatchingStatements($configModel->getModelIri(),
                'http://ns.ontowiki.net/SysOnt/Anonymous',
                'http://ns.ontowiki.net/SysOnt/grantModelEdit',
                array('value' => 'http://ns.ontowiki.net/SysOnt/AnyModel ', 'type'  => 'uri'), $options); //false??
        
        $groups = array('Contractors' => 'http://localhost/OntoWiki/Config/Contractors',
                        'Suppliers'   => 'http://localhost/OntoWiki/Config/Suppliers');
        foreach ($groups as $name => $group) {
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
                array('value' => 'http://rdfs.org/sioc/ns#Usergroup', 'type'  => 'uri'),
                false);
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://ns.ontowiki.net/SysOnt/grantModelView',
                array('value' => 'http://ld.opendata.cz/resource/', 'type'  => 'uri'),
                false);
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://ns.ontowiki.net/SysOnt/denyModelView',
                array('value' => 'http://ns.ontowiki.net/SysBase/', 'type'  => 'uri'),
                false);
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://ns.ontowiki.net/SysOnt/denyModelView',
                array('value' => 'http://ns.ontowiki.net/SysOnt/', 'type'  => 'uri'),
                false);
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://ns.ontowiki.net/SysOnt/denyModelView',
                array('value' => 'http://localhost/OntoWiki/Config/', 'type'  => 'uri'),
                false);
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://ns.ontowiki.net/SysOnt/grantAccess',
                array('value' => 'http://ns.ontowiki.net/SysOnt/Login', 'type'  => 'uri'),
                false);
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://ns.ontowiki.net/SysOnt/grantAccess',
                array('value' => 'http://ns.ontowiki.net/SysOnt/Rollback', 'type'  => 'uri'),
                false);
            /*$store->addStatement($configModel->getModelIri(),
                $group,
                'http://www.w3.org/2000/01/rdf-schema#comment',
                array('value' => 'User group for *****', 'type'  => 'literal'),
                false);*/
            $store->addStatement($configModel->getModelIri(),
                $group,
                'http://www.w3.org/2000/01/rdf-schema#label',
                array('value' => $name, 'type'  => 'literal'),
                false);
        }
    }

?>

<h2>Welcome</h2>
<p>This application helps search and publish public contracts.</p>