<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $user = $ow->getUser();
    $wikiBaseUri = $GLOBALS["wBaseUri"];
?>
<div id="accountbox" class="leftbox">
<?php if (!$user->isAnonymousUser()) {
    $be = getUserBusiness($ow);
    
?>
    <h3>My Account</h3>
    <p>Logged in as <em><?php echo $user->getUsername(); ?></em></p>
    <ul>
        <li><a href="?page=preferences&amp;cht=<?php echo genChT(); ?>">Preferences</a></li>
<?php if ($be !== false) { ?>
        <li><a href="?page=businessentity&amp;uri=<?php echo urlencode($be[0]); ?>">Edit my business entity</a></li>
<?php } ?>
        <li><a href="<?php echo $wikiBaseUri; ?>application/logout">Log out</a></li>
        <li><a href="view">Enter the backend</a> <br /><small>(for advanced users only)</small></li>
    </ul>
<?php } else { ?>
    <h3>Log in</h3>
    <ul>
        <li><a href="?page=login&amp;cht=<?php echo genChT(); ?>">Log in</a></li>
        <li><a href="?page=signup&amp;cht=<?php echo genChT(); ?>">Sign up</a></li>
        <li><a href="view">Enter the backend</a> <br /><small>(for advanced users only)</small></li>
    </ul>
<?php } ?>
</div>