<?php
    $templateData = loadData();
    $ow = OntoWiki::getInstance();
    $user = $ow->getUser();
    
    if (isset($_REQUEST["page"]) &&
       ($_REQUEST["page"] == "searchcontracts" ||
        $_REQUEST["page"] == "searchmycontracts"
       ))
    {
?>
<div id="filterbox" class="rightbox">
    <h3>Filter</h3>
    <table>
    <!--<tr><th colspan="2">Price</th></tr>
    <tr><td>Min:</td><td><input type="text" style="width:100%;" /></td></tr>
    <tr><td>Max:</td><td><input type="text" style="width:100%;" /></td></tr>-->
    </table>
</div>
<?php
    }